### ISSUE TITLE
Owner is not actionable

### ISSUE THREAD

**Issue by Flukas88** [netr0m/az-pim-cli#13]
When I try to activate the owner role

![screenshot-2](https://github.com/netr0m/az-pim-cli/assets/2707529/215d8de2-fcc8-4e6b-8c8d-bfb64c52a3ae)

I get an error

**2024/05/10 15:05:24 ERROR: The role assignment validation failed with status 'PendingEvaluation'**

**Comment by netr0m** [comment]
Thanks for the report! It looks like the role you're trying to activate requires evaluation (i.e. approval) from another party (e.g. a manager) - could that be the case? (ref. https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-resource-roles-approval-workflow#view-pending-requests)

The current solution [attempts to validate the request](https://github.com/netr0m/az-pim-cli/blob/26703f15f7c11b1d2296ef393a1efa52330a29cd/pkg/pim/client.go#L186), and [expects the `status` of the request to be 'Granted'](https://github.com/netr0m/az-pim-cli/blob/26703f15f7c11b1d2296ef393a1efa52330a29cd/pkg/pim/client.go#L151) before requesting the actual role activation. Seeing as the `status` returned by your request is 'PendingEvaluation', it fails. None of the roles I have available require approval, so I have never encountered this issue before. I will create a PR with a fix for this issue!

**Comment by netr0m** [comment]
@Flukas88 I've issued a fix in #14 which I believe should resolve this issue. Please give it another go with the latest version, and let me know if your issue persists :smile:

**Comment by Flukas88** [comment]
will check asap and get back to you
