### ISSUE TITLE
What OS is this for please?

### ISSUE THREAD

**Issue by kanekennedy** [netr0m/az-pim-cli#15]
Running the Go install doesn't appear to put the binary on the system anywhere.

Errors on building on Intel Mac Sonoma 14.5
```
go build
package github.com/netr0m/az-pim-cli
	imports github.com/netr0m/az-pim-cli/cmd
	imports github.com/netr0m/az-pim-cli/pkg/pim
	imports github.com/Azure/azure-sdk-for-go/sdk/azidentity: build constraints exclude all Go files in /Users/xxxx/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azidentity@v1.5.2
```
Tried with no effect

sudo
CGO_ENABLED=1
export GOOS=darwin
export GOARCH=amd64

**Comment by netr0m** [comment]
Hi, thanks for the report. Please provide the output of commands:
- `go version`
- `go env`

**Comment by netr0m** [comment]
It should be OS-independent, though I have only tested it on Linux (Arch) myself.
I also tried to build for MacOS with `GOOS=darwin GOARCH=amd64 go build` just now, both on my machine and through a Docker container with 
```bash
docker run -it golang bash
git clone https://github.com/netr0m/az-pim-cli.git
cd az-pim-cli
GOOS=darwin GOARCH=amd64 go build
```
which both ran without error.

`go build` should produce a binary in the current working directory, i.e. a file named `az-pim-cli`. A successful run of that command should **not** produce any output to the console.
The output from your command;
```
package github.com/netr0m/az-pim-cli
	imports github.com/netr0m/az-pim-cli/cmd
	imports github.com/netr0m/az-pim-cli/pkg/pim
	imports github.com/Azure/azure-sdk-for-go/sdk/azidentity: build constraints exclude all Go files in /Users/xxxx/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azidentity@v1.5.2
```
indicates that something failed.

A search for 'build constrains exclude all Go files in' got me [this answer on StackOverflow](https://stackoverflow.com/a/73531307), which recommends trying to run `go clean -modcache` before retrying the `go build` command.

If this doesn't get you anywhere, please let me know.

**Comment by kanekennedy** [comment]
Thank you,

Really sorry, didn't think to check Go version as I rarely use it.  I was on v1.17, upgrading to 1.22.3 allowed it to build correctly.

I still couldn't find the binary anywhere using the go install method, not sure whats going on there...
```
╰─➤  go install github.com/netr0m/az-pim-cli@latest
go: downloading github.com/netr0m/az-pim-cli v0.0.0-20240522110536-57e447247280
```
thats all it does.

**Comment by netr0m** [comment]
`go install` installs the binary in `$GOPATH/bin`;
> Executables are installed in the directory named by the GOBIN environment variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH environment variable is not set.
[from https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies]

So, if you've added `$GOPATH` to your `PATH`, the command `az-pim-cli` should be available in your shell.

```bash
docker run --rm -it golang bash
root@b89582da6c93:/go# go install github.com/netr0m/az-pim-cli@latest
go: downloading github.com/netr0m/az-pim-cli v0.0.0-20240522110536-57e447247280
go: downloading github.com/spf13/cobra v1.8.0
go: downloading github.com/spf13/viper v1.18.2
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.5.2
go: downloading github.com/Azure/azure-sdk-for-go/sdk/azcore v1.11.1
go: downloading github.com/golang-jwt/jwt/v5 v5.2.1
go: downloading github.com/google/uuid v1.6.0
go: downloading github.com/spf13/cast v1.6.0
go: downloading github.com/sagikazarmark/slog-shim v0.1.0
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/spf13/afero v1.11.0
go: downloading github.com/fsnotify/fsnotify v1.7.0
go: downloading github.com/subosito/gotenv v1.6.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/magiconair/properties v1.8.7
go: downloading github.com/pelletier/go-toml/v2 v2.1.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading golang.org/x/text v0.14.0
go: downloading github.com/Azure/azure-sdk-for-go/sdk/internal v1.5.2
go: downloading golang.org/x/sys v0.18.0
go: downloading github.com/AzureAD/microsoft-authentication-library-for-go v1.2.2
go: downloading golang.org/x/crypto v0.21.0
go: downloading golang.org/x/net v0.23.0
go: downloading github.com/kylelemons/godebug v1.1.0
go: downloading github.com/pkg/browser v0.0.0-20240102092130-5ac0b6a4141c
root@b89582da6c93:/go# which az-pim-cli
/go/bin/az-pim-cli
```
