### ISSUE TITLE
Unauthorized after running az login

### ISSUE THREAD

**Issue by Trulsaa** [netr0m/az-pim-cli#5]
I get the following error message after running `az logine` and then `az-pim-cli list`

```log
The upstream API responded with status 401 Unauthorized: {"errorCode":"BadRequest","message":"Bad request.","instanceAnnotations":[]}
```

I have been looking for a tool like this for a while. It would be awesome if it worked for me. Is this something you could help me with. Or point me to the part of the code where this happens?

**Comment by netr0m** [comment]
Hi! I haven't been using this tool for a while, but I tested it myself just now and it seems the API endpoints that the solution uses have changed (probably alongside the transition from Microsoft Active Directory => Entra ID). I will have a look at what's changed!

**Comment by Trulsaa** [comment]
Awesome! Thank you. `az-pim-cli list` now returns the list of Azure Resources it is possible to activate. I am missing the list of Groups that i am able to activate. Are you able to point me in a direction of where in the code this can be added?

Also when using `az-pim-cli activate -s <sub> -r <role>`. It activates a different subscription than the one specified with the `-s` flage 🤷

**Comment by netr0m** [comment]
> Awesome! Thank you. `az-pim-cli list` now returns the list of Azure Resources it is possible to activate. I am missing the list of Groups that i am able to activate. Are you able to point me in a direction of where in the code this can be added?
> 
> Also when using `az-pim-cli activate -s <sub> -r <role>`. It activates a different subscription than the one specified with the `-s` flage 🤷

Should be resolved now! Apparently, I've only been using the `-p` (prefix) flag for subscription selection, and hadn't discovered a logical bug when using `-s` instead. Thanks for the report!
