### ISSUE TITLE
Allow to specify ticket system and ticket number for activation request

### ISSUE THREAD

**Issue by breml** [netr0m/az-pim-cli#52]
### Welcome

- [X] Yes, I've searched similar [issues on GitHub](https://github.com/netr0m/az-pim-cli/issues) and didn't find any.

### Is your feature request related to a problem? Please describe

In my case, I am required to provide the ticket system and the ticket number for each PIM request.

### Describe the solution you'd like

Accept ticket system and ticket number as additional flags for the activation request.
For the ticket system, it would be nice to have it in the config file as well, since it is basically static.

### Describe alternatives you've considered

-

**Comment by netr0m** [comment]
This has now been implemented on the `main` branch. You may also [specify these options in the configuration file](https://github.com/netr0m/az-pim-cli/tree/main?tab=readme-ov-file#yaml-file)
